/**
 * Created by alexanderbelenov on 19.06.2022.
 */

public with sharing class Constants {
    public static final String ACCESS_LEVEL_EDIT = 'Edit';
    public static final String ACCESS_LEVEL_NONE = 'None';
    public static final String ROW_CAUSE_MANUAL = 'Manual';

    public static final String ERROR_ALREADY_EXISTS = 'Already exists';
    public static final String ERROR_HAS_CHILD_TERRITORIES = 'Has child territories';
    public static final String ERROR_HAS_ASSIGNED_ACCOUNTS = 'Has assigned accounts';
}