/**
 * Created by alexanderbelenov on 22.06.2022.
 */

@IsTest
private class PermissionServiceTest {
    private PermissionService service = PermissionService.getInstance();

    @IsTest static void testGetAccountShares() {

    }

    @IsTest static void testGetContactShares() {
    }

    @IsTest static void testGetAccountIdsWithoutPermissions() {

    }

    @IsTest static void testGetContactIdsWithoutPermissions() {

    }

    @IsTest static void testRemoveAccountPermissions() {

    }

}